// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://bknhtfhlokneunwxuqtl.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbmh0Zmhsb2tuZXVud3h1cXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyODc2NzIsImV4cCI6MjA0ODg2MzY3Mn0.nYx018bS5UegG4kr7zqPti3hNQjUhPIA-_cfpc1jR_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);